// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGFvoBMXGfZL-jKO7J6GS_fVFUsE0ysU',
    appId: '1:1027997293594:web:c41ad7c67756fcccba85a3',
    messagingSenderId: '1027997293594',
    projectId: 'fir-my-medicines-app',
    authDomain: 'fir-my-medicines-app.firebaseapp.com',
    storageBucket: 'fir-my-medicines-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGX1U2FAaopkK59RMhYXeWxXG_BzTsieE',
    appId: '1:1027997293594:android:cfc4d5f93bc5a0dfba85a3',
    messagingSenderId: '1027997293594',
    projectId: 'fir-my-medicines-app',
    storageBucket: 'fir-my-medicines-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcusvQoacLFuktskwBJMUN2ZUuwD4DsO4',
    appId: '1:1027997293594:ios:13b561beef62e257ba85a3',
    messagingSenderId: '1027997293594',
    projectId: 'fir-my-medicines-app',
    storageBucket: 'fir-my-medicines-app.appspot.com',
    iosBundleId: 'com.example.myMedicines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcusvQoacLFuktskwBJMUN2ZUuwD4DsO4',
    appId: '1:1027997293594:ios:13b561beef62e257ba85a3',
    messagingSenderId: '1027997293594',
    projectId: 'fir-my-medicines-app',
    storageBucket: 'fir-my-medicines-app.appspot.com',
    iosBundleId: 'com.example.myMedicines',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqGFvoBMXGfZL-jKO7J6GS_fVFUsE0ysU',
    appId: '1:1027997293594:web:b62e9f032752c1a8ba85a3',
    messagingSenderId: '1027997293594',
    projectId: 'fir-my-medicines-app',
    authDomain: 'fir-my-medicines-app.firebaseapp.com',
    storageBucket: 'fir-my-medicines-app.appspot.com',
  );

}